// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTR2I0wISJfgzOY5if9O6eEwHLwwlTu_I',
    appId: '1:24037614646:web:ef481417f76feeb2c2a497',
    messagingSenderId: '24037614646',
    projectId: 'whatsapp-backend-f5025',
    authDomain: 'whatsapp-backend-f5025.firebaseapp.com',
    storageBucket: 'whatsapp-backend-f5025.appspot.com',
    measurementId: 'G-GY0YWDZM6N',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBx9yHF3GapBrFi6Cln4jsmWz54vjlhHLQ',
    appId: '1:24037614646:ios:7626c9d93107aa8cc2a497',
    messagingSenderId: '24037614646',
    projectId: 'whatsapp-backend-f5025',
    storageBucket: 'whatsapp-backend-f5025.appspot.com',
    iosClientId: '24037614646-b52rrqho97lvqb2157bg08e0pdasl667.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsappClone',
  );
}
